config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :orders
  resources :taxis
  resources :person_in_charges
  resource :authentication_token, only: [:update, :destroy]
  devise_for :users, controllers: { sessions: "sessions" }

  root 'contents#index'

end

app/models/taxi.rb
class Taxi < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :orders, dependent: :destroy

  acts_as_paranoid
end

app/controllers/taxis_controller.rb
class TaxisController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_taxi, only: [:show, :edit, :update, :destroy]

  # GET /taxis
  # GET /taxis.json
  def index
    @taxis = Taxi.where(["user_id =?", current_user.id]).order("name").page params[:page]
  end

  # GET /taxis/1
  # GET /taxis/1.json
  def show
  end

  # GET /taxis/new
  def new
    @taxi = Taxi.new
  end

  # GET /taxis/1/edit
  def edit
  end

  # POST /taxis
  # POST /taxis.json
  def create
    @taxi = Taxi.new(taxi_params.merge(user: current_user))

    respond_to do |format|
      if @taxi.save
        format.html { redirect_to @taxi, notice: t("activerecord.models.taxi") + t("messages.created") }
        format.json { render :show, status: :created, location: @taxi }
      else
        format.html { render :new }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taxis/1
  # PATCH/PUT /taxis/1.json
  def update
    respond_to do |format|
      if @taxi.update(taxi_params)
        format.html { redirect_to @taxi, notice: t("activerecord.models.taxi") + t("messages.updated") }
        format.json { render :show, status: :ok, location: @taxi }
      else
        format.html { render :edit }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxis/1
  # DELETE /taxis/1.json
  def destroy
    @taxi.destroy
    respond_to do |format|
      format.html { redirect_to taxis_url, notice: t("activerecord.models.taxi") + t("messages.destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taxi
      @taxi = Taxi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taxi_params
      params.require(:taxi).permit(:user_id, :name, :type_name)
    end
end

app/helpers/taxis_helper.rb
module TaxisHelper
end

app/views/taxis/_form.html.haml
= form_for @taxi do |f|
  - if @taxi.errors.any?
    #error_explanation
      %h2= "#{pluralize(@taxi.errors.count, "error")} prohibited this taxi from being saved:"
      %ul
        - @taxi.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.label :type_name
    = f.text_field :type_name, class: "form-control"
  .actions
    = link_to t("links.back"), taxis_path, class: "btn btn-default"
    = f.submit class: "btn btn-primary"

app/views/taxis/edit.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1
      %h2.text-center= t("activerecord.models.taxi") + t("views.edit")
      = render 'form'

app/views/taxis/index.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1.text-center
      %h2= t("activerecord.models.taxi") + t("views.index")

%section
  .container
    = paginate @taxis
    - @taxis.each do |taxi|
      .row
        .col-lg-12.text-center
          %h2
            = taxi.name
            = surround "（", "）" do
              = taxi.type_name
          = link_to t("links.show"), taxi, class: "btn btn-sm btn-info"
          = link_to t("links.edit"), edit_taxi_path(taxi), class: "btn btn-sm btn-success"
          = link_to t("links.destroy"), taxi, method: :delete, data: { confirm: t("messages.are_you_sure") }, class: "btn btn-sm btn-danger"
      %hr.small
    / /.row
    = paginate @taxis
  / /.container

.text-center= link_to t("activerecord.models.taxi") + t("links.new"), new_taxi_path, class: "btn btn-primary"

app/views/taxis/new.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1
      %h2.text-center= t("activerecord.models.taxi") + t("views.new")
      = render 'form'

app/views/taxis/show.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1.text-center
      %h2= t("activerecord.models.taxi") + t("views.show")

%section
  .container
    .row
      .col-lg-12.text-center
        %h2= @taxi.name
        %h3= @taxi.type_name
        = link_to t("links.back"), taxis_path, class: "btn btn-default"
        = link_to t("links.edit"), edit_taxi_path(@taxi), class: "btn btn-success"
        = link_to t("links.destroy"), @taxi, method: :delete, data: { confirm: t("messages.are_you_sure") }, class: "btn btn-danger"
      %hr.small
    / /.row
  / /.container