config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :orders
  resources :taxis
  resources :person_in_charges
  resource :authentication_token, only: [:update, :destroy]
  devise_for :users, controllers: { sessions: "sessions" }

  root 'contents#index'

end

app/models/person_in_charge.rb
class PersonInCharge < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :orders, dependent: :destroy

  acts_as_paranoid
end

app/controllers/person_in_charges_controller.rb
class PersonInChargesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_person_in_charge, only: [:show, :edit, :update, :destroy]

  # GET /person_in_charges
  # GET /person_in_charges.json
  def index
    @person_in_charges = PersonInCharge.where(["user_id = ?" ,current_user.id]).page params[:page]
  end

  # GET /person_in_charges/1
  # GET /person_in_charges/1.json
  def show
  end

  # GET /person_in_charges/new
  def new
    @person_in_charge = PersonInCharge.new
  end

  # GET /person_in_charges/1/edit
  def edit
  end

  # POST /person_in_charges
  # POST /person_in_charges.json
  def create
    @person_in_charge = PersonInCharge.new(person_in_charge_params.merge(user: current_user))

    respond_to do |format|
      if @person_in_charge.save
        format.html { redirect_to @person_in_charge, notice: t("activerecord.models.person_in_charge") + t("messages.created") }
        format.json { render :show, status: :created, location: @person_in_charge }
      else
        format.html { render :new }
        format.json { render json: @person_in_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /person_in_charges/1
  # PATCH/PUT /person_in_charges/1.json
  def update
    respond_to do |format|
      if @person_in_charge.update(person_in_charge_params)
        format.html { redirect_to @person_in_charge, notice: t("activerecord.models.person_in_charge") + t("messages.updated") }
        format.json { render :show, status: :ok, location: @person_in_charge }
      else
        format.html { render :edit }
        format.json { render json: @person_in_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /person_in_charges/1
  # DELETE /person_in_charges/1.json
  def destroy
    @person_in_charge.destroy
    respond_to do |format|
      format.html { redirect_to person_in_charges_url, notice: t("activerecord.models.person_in_charge") + t("messages.destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person_in_charge
      @person_in_charge = PersonInCharge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_in_charge_params
      params.require(:person_in_charge).permit(:user_id, :name)
    end
end

app/helpers/person_in_charges_helper.rb
module PersonInChargesHelper
end

app/views/person_in_charges/_form.html.haml
= form_for @person_in_charge do |f|
  - if @person_in_charge.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person_in_charge.errors.count, "error")} prohibited this person_in_charge from being saved:"
      %ul
        - @person_in_charge.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .actions
    = f.submit class: "btn btn-default"

app/views/person_in_charges/edit.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1
      %h2.text-center= t("activerecord.models.person_in_charge") + t("views.edit")
      = render 'form'
      = link_to t("links.back"), person_in_charges_path, class: "btn btn-default"

app/views/person_in_charges/index.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1.text-center
      %h2= t("activerecord.models.person_in_charge") + t("views.index")

%section
  .container
    = paginate @person_in_charges
    - @person_in_charges.each do |person_in_charge|
      .row
        .col-lg-12.text-center
          %h2= person_in_charge.name
          = link_to t("links.show"), person_in_charge, class: "btn btn-default btn-sm"
          = link_to t("links.edit"), edit_person_in_charge_path(person_in_charge), class: "btn btn-default btn-sm"
          = link_to t("links.destroy"), person_in_charge, method: :delete, data: { confirm: t("messages.are_you_sure") }, class: "btn btn-default btn-sm"
      %hr.small
    / /.row
    = paginate @person_in_charges
  / /.container

.text-center= link_to t("activerecord.models.person_in_charge") + t("links.new"), new_person_in_charge_path, class: "btn btn-default"

app/views/person_in_charges/new.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1
      %h2.text-center= t("activerecord.models.person_in_charge") + t("views.new")
      = render 'form'
      = link_to t("links.back"), person_in_charges_path, class: "btn btn-default"

app/views/person_in_charges/show.html.haml
.container
  .row
    .col-lg-10.col-lg-offset-1.text-center
      %h2= t("activerecord.models.person_in_charge") + t("views.index")

%section
  .container
    .row
      .col-lg-12.text-center
        %h2= @person_in_charge.name
        = link_to t("links.edit"), edit_person_in_charge_path(@person_in_charge), class: "btn btn-default"
        = link_to t("links.destroy"), @person_in_charge, method: :delete, data: { confirm: t("messages.are_you_sure") }, class: "btn btn-default"
    %hr.small
  / /.row
  / /.container

.text-center
  = link_to t("links.back"), person_in_charges_path, class: "btn btn-default"